In [0]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [0]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.0877e-35, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix:



In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3376, 0.0750, 0.1745],
        [0.3842, 0.3180, 0.5400],
        [0.3890, 0.9760, 0.4992],
        [0.9816, 0.0996, 0.0022],
        [0.8178, 0.8335, 0.2490]])


Construct a matrix filled zeros and of dtype long:



In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 2.2937,  0.6344,  0.1552],
        [-0.4246,  0.2412,  0.7141],
        [ 0.3029, -0.1319, -1.4362],
        [-0.3377,  0.8790,  0.8191],
        [-1.8966, -1.4801, -1.5848]])


Get its size:



In [7]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 2.9754,  1.1990,  0.9393],
        [ 0.3550,  0.4999,  1.2390],
        [ 0.6037,  0.7966, -0.6484],
        [-0.1395,  1.4253,  0.8450],
        [-1.1150, -0.6143, -1.3881]])


Addition: syntax 2



In [9]:
print(torch.add(x, y))

tensor([[ 2.9754,  1.1990,  0.9393],
        [ 0.3550,  0.4999,  1.2390],
        [ 0.6037,  0.7966, -0.6484],
        [-0.1395,  1.4253,  0.8450],
        [-1.1150, -0.6143, -1.3881]])


Addition: providing an output tensor as argument



In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.9754,  1.1990,  0.9393],
        [ 0.3550,  0.4999,  1.2390],
        [ 0.6037,  0.7966, -0.6484],
        [-0.1395,  1.4253,  0.8450],
        [-1.1150, -0.6143, -1.3881]])


Addition: in-place



In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 2.9754,  1.1990,  0.9393],
        [ 0.3550,  0.4999,  1.2390],
        [ 0.6037,  0.7966, -0.6484],
        [-0.1395,  1.4253,  0.8450],
        [-1.1150, -0.6143, -1.3881]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [12]:
print(x[:, 1])

tensor([ 0.6344,  0.2412, -0.1319,  0.8790, -1.4801])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [19]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())
print(z)
print(x)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[-0.3837,  0.4874,  1.3080,  0.8727,  1.4889,  0.7413,  2.2086,  2.2039],
        [-1.6000, -0.4351, -1.1452,  0.0748, -0.0788,  0.6351, -0.0812, -0.4917]])
tensor([[-0.3837,  0.4874,  1.3080,  0.8727],
        [ 1.4889,  0.7413,  2.2086,  2.2039],
        [-1.6000, -0.4351, -1.1452,  0.0748],
        [-0.0788,  0.6351, -0.0812, -0.4917]])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [20]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1541])
0.15407794713974


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [21]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [22]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [23]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [24]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!